apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgres-secret.yml
- postgres-pvc.yml
- postgres-deployment.yml
- postgres-service.yml
- api-deployment.yml
- api-service.yml
- api-hpa.yml
- frontend-deployment.yml
- frontend-service.yml
- frontend-hpa.yml
- prometheus-config.yml
- prometheus-pvc.yml
- prometheus-deployment.yml
- prometheus-service.yml
- grafana-pvc.yml
- grafana-config.yml
- grafana-deployment.yml
- grafana-service.yml