apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  prometheus.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: false
  provider.yml: |
    apiVersion: 1
    providers:
      - name: Kongsberg monitoring
        orgId: 1
        folder: Monitoring
        type: file
        disableDeletion: false
        allowUiUpdates: true
        updateIntervalSeconds: 30
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: false