{{- if not .Values.grafana.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafana.admin.secretName }}
type: Opaque
stringData:
  user: {{ .Values.grafana.admin.user | quote }}
  password: {{ .Values.grafana.admin.password | quote }}
{{- end }}