apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
stringData:
  username: postgres
  password: postgres
  database: textsdb
  database-url: postgresql+psycopg2://postgres:postgres@postgres:5432/textsdb