{{- if not .Values.postgres.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.auth.secretName }}
type: Opaque
stringData:
  username: {{ .Values.postgres.auth.username | quote }}
  password: {{ .Values.postgres.auth.password | quote }}
  database: {{ .Values.postgres.auth.database | quote }}
  database-url: {{ printf "postgresql+psycopg2://%s:%s@postgres:5432/%s" .Values.postgres.auth.username .Values.postgres.auth.password .Values.postgres.auth.database | quote }}
{{- end }}