apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: api
        metrics_path: /metrics
        static_configs:
          - targets:
            - api:8000
      {{- if .Values.monitoring.pushgateway.enabled }}
      - job_name: pushgateway
        static_configs:
          - targets:
            - pushgateway:9091
      {{- end }}
      {{- if .Values.monitoring.cadvisor.enabled }}
      - job_name: cadvisor
        static_configs:
          - targets:
            - cadvisor:8080
      {{- end }}