imagePullSecrets:
  - acr-pull-secret

api:
  image:
    repository: knsberg.azurecr.io/praktyki-api
  frontendOrigin: "http://frontend.dev.local"

frontend:
  image:
    repository: knsberg.azurecr.io/praktyki-frontend

postgres:
  image:
    repository: knsberg.azurecr.io/praktyki-postgres
  auth:
    password: postgres

prometheus:
  image:
    repository: knsberg.azurecr.io/praktyki-prom
  externalUrl: "http://prometheus.dev.local"

grafana:
  image:
    repository: knsberg.azurecr.io/praktyki-grafana
  server:
    rootUrl: "http://grafana.dev.local"
    domain: grafana.dev.local

ingress:
  hosts:
    frontend: frontend.dev.local
    api: api.dev.local
    grafana: grafana.dev.local
    prometheus: prometheus.dev.local
