imagePullSecrets:
  - acr-pull-secret

api:
  image:
    repository: knsberg.azurecr.io/praktyki-api
  frontendOrigin: "http://frontend.local"

frontend:
  image:
    repository: knsberg.azurecr.io/praktyki-frontend

postgres:
  image:
    repository: knsberg.azurecr.io/praktyki-postgres

prometheus:
  image:
    repository: knsberg.azurecr.io/praktyki-prom
  externalUrl: "http://prometheus.local"

grafana:
  image:
    repository: knsberg.azurecr.io/praktyki-grafana

grafana:
  server:
    rootUrl: "http://grafana.local"
    domain: grafana.local
