imagePullSecrets:
  - acr-pull-secret

api:
  image:
    repository: knsberg.azurecr.io/praktyki-api
  frontendOrigin: "https://frontend.dev.local"

frontend:
  image:
    repository: knsberg.azurecr.io/praktyki-frontend

postgres:
  image:
    repository: knsberg.azurecr.io/praktyki-postgres
  auth:
    password: postgres

prometheus:
  image:
    repository: knsberg.azurecr.io/praktyki-prom
  externalUrl: "https://prometheus.dev.local"

grafana:
  image:
    repository: knsberg.azurecr.io/praktyki-grafana
  server:
    rootUrl: "https://grafana.dev.local"
    domain: grafana.dev.local

ingress:
  hosts:
    frontend: frontend.dev.local
    api: api.dev.local
    grafana: grafana.dev.local
    prometheus: prometheus.dev.local
  tls:
    enabled: true
    secretName: praktyki-tls
    redirectHttp: true
