imagePullSecrets:
  - acr-pull-secret

api:
  image:
    repository: kmprod.azurecr.io/praktyki-api
  frontendOrigin: "http://frontend.prod.local"

frontend:
  image:
    repository: kmprod.azurecr.io/praktyki-frontend

postgres:
  image:
    repository: kmprod.azurecr.io/praktyki-postgres

prometheus:
  image:
    repository: kmprod.azurecr.io/praktyki-prom
  externalUrl: "http://prometheus.prod.local"

grafana:
  image:
    repository: kmprod.azurecr.io/praktyki-grafana

  server:
    rootUrl: "http://grafana.prod.local"
    domain: grafana.prod.local

ingress:
  hosts:
    frontend: frontend.prod.local
    api: api.prod.local
    grafana: grafana.prod.local
    prometheus: prometheus.prod.local
  tls:
    enabled: false
    secretName: praktyki-tls

  certManager:
    enabled: false
    clusterIssuer: letsencrypt-prod
